substitutions:
  uart_tx_pin: GPIO19
  uart_rx_pin: GPIO18

uart:
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
